server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/**
        - id: scheduler-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/scheduler/**,/api/shifts/**,/api/shifts/unassigned, /api/shift-assignments/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - RemoveRequestHeader

app:
  jwt:
    secret: ${JWT_SECRET:change-me}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG