server:
  port: 8080

spring:
  application:
    name: api-gateway

app:
  jwt:
    secret: ${JWT_SECRET:change-me}


  cloud:
    gateway:
      routes:
        # Route to user-service
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**

        # Route to item-service
        - id: item-service
          uri: http://localhost:8082
          predicates:
            - Path=/items/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - RemoveRequestHeader=Cookie
