
services:
  postgres:
    image: postgres:16
    container_name: user-service-db
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d users_db"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: