services:
  postgres:
    image: postgres:16
    container_name: scheduler-service-db
    environment:
      POSTGRES_DB: scheduler_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d scheduler_db"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: