server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/users_db}
    username: ${DB_USER:user}
    password: ${DB_PASS:pass}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"

app:
  jwt:
    secret: ${JWT_SECRET:change-me} # Change on production
    expiryMinutes: ${JWT_EXP_MIN:30}
