name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: 
          - user-service
          
    
    defaults:
      run:
        working-directory: services/${{ matrix.service }}/devops_mirco_project
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build ${{ matrix.service }}
        run: mvn clean compile

      - name: Run tests for ${{ matrix.service }}
        run: mvn test