name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build user-service
        run: |
          cd services/user-service/devops_mirco_project
          mvn clean compile

      - name: Run tests
        run: |
          cd services/user-service/devops_mirco_project
          mvn test